dist: bionic
os: linux

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - DOCKER_BUILDKIT=1
    - DOCKER_CLI_EXPERIMENTAL=enabled

services:
  - docker

before_script:
  - chmod -R a+x scripts

script: #todo: delete script
  - ./scripts/deploy.sh

before_deploy:
  - sudo apt-get update
  - sudo apt-get upgrade

deploy:
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      branch: master