dist: bionic
os: linux
arch:
  - arm64

services:
  - docker

script: #todo: delete script
  - provider: script
    script: bash ./scripts/deploy.sh

deploy:
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      branch: master