dist: bionic
os: linux

env:
  global:
    - DOCKER_BUILDKIT=1
    - DOCKER_CLI_EXPERIMENTAL=enabled

services:
  - docker

before_script:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - chmod -R a+x scripts

script: #todo: delete script
  - ./scripts/deploy.sh

before_deploy:
  - sudo apt-get update
  - sudo apt-get upgrade

deploy:
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      branch: master