dist: bionic
os: linux
arch:
  - arm64

services:
  - docker

before_install:
  - docker build -t "$DOCKERHUB_LOGIN"/temperature_project:scanner-"$TRAVIS_CPU_ARCH" -f ./src/TemperatureScanner/Dockerfile ./src
  - docker build -t "$DOCKERHUB_LOGIN"/temperature_project:nginx-"$TRAVIS_CPU_ARCH" -f ./src/nginx/Dockerfile ./src/nginx/

script:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_LOGIN" --password-stdin
  - docker push "$DOCKERHUB_LOGIN"/temperature_project:scanner-"$TRAVIS_CPU_ARCH"
  - docker push "$DOCKERHUB_LOGIN"/temperature_project:nginx-"$TRAVIS_CPU_ARCH"
