dist: bionic
os: linux
arch:
  - arm64

services:
  - docker

before_script:
  - chmod -R a+x scripts

script: #todo: delete script
  - ./scripts/deploy.sh

deploy:
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      branch: master