dist: bionic
os: linux

env:
  - DOCKER_BUILDKIT=1
  - DOCKER_CLI_EXPERIMENTAL=enabled
  
services:
  - docker

before_script:
  - chmod -R a+x scripts

script: #todo: delete script
  - ./scripts/deploy.sh

deploy:
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      branch: master