dist: bionic
os: linux

services:
  - docker

before_script:
  - chmod -R a+x scripts
  - export DOCKER_BUILDKIT=1
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - sudo apt-get update
  - sudo apt-get upgrade

script: #todo: delete script
  - ./scripts/deploy.sh

before_deploy:
  - sudo apt-get update
  - sudo apt-get upgrade

deploy:
  - provider: script
    script: bash ./scripts/deploy.sh
    on:
      branch: master