version: '3'
services:
    temperatureScanner:
        image: gagyn/temperature_project
        restart: "unless-stopped"
        devices: 
            - "/dev/ttyACM0:/dev/ttyACM0"
        volumes: 
            - ./config.json:/app/config.json
            - ./logs:/app/logs
        ports: 
            - "5000:5000"
