FROM python:3

WORKDIR /app

COPY ./src/TemperatureScanner/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src .
RUN pip install .
EXPOSE 8080

CMD ["uwsgi", "TemperatureScanner/app.ini"]